### ISSUE TITLE
Add support for adding raw content from stdin

### ISSUE THREAD

**Issue by facundovictor** [cabinet/cabinet-cli#7]
After the chat within the PR #6. It should be nice to update the way the raw content is being entered without the editor. I think it should be great if could do something like:

    `cab add awesome-item -c < some_file`

We may need to use a flag to say we are going to use **stdin** so we wait until the content is "entered" to ask for the password.

**Comment by ivanalejandro0** [comment]
Supporting pipes allows us to do other kinds of redirections as well, examples:
`echo "my supersecret" | cab add something`
`cat some_file | cab add something2`
